network:
  company_income_statement_url_prefix: 'https://www.macrotrends.net/stocks/charts'
  company_income_statement_url_suffix: 'income-statement'
  num_of_stocks_to_collect_data_from: 1000

page_locator:
  income_statement_table_id: 'contenttablejqxgrid'
  attribute_row_css_selector: 'div[role="row"]'
  grid_cell_css_selector: 'div[role="gridcell"]'

data_table:
  attributes: ["Revenue", "Cost Of Goods Sold", "Gross Profit", "Research And Development Expenses", 
    "SG&A Expenses", "Other Operating Income Or Expenses", "Operating Expenses", "Operating Income", 
    "Total Non-Operating Income/Expense", "Pre-Tax Income", "Income Taxes", "Income After Taxes", 
    "Other Income", "Income From Continuous Operations", "Income From Discontinued Operations", "Net Income", 
    "EBITDA", "EBIT", "Basic Shares Outstanding", "Shares Outstanding", "Basic EPS", "EPS - Earnings Per Share"]
  years_of_records_to_collect: 5


file:
  base_stocks_desctiptive_csv_file_path: 'generated_csv_files/stocks_descriptive/stocks_descriptive_2024-06-13.csv'
  generated_csv_files_sub_folder: 'company_income_statement'